FROM php:apache

RUN apt-get -y update
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt-get -y update
RUN apt-get -y install php7-mysql

# Environment variables to configure php
COPY apache/sites-enabled/* /etc/apache2/sites-enabled/
